### ISSUE TITLE
Authentication using ajax only with json requests/responces

### ISSUE THREAD

**Issue by JosephBuchma** [kasperisager/sails-generate-auth#141]
Hi. I need to implement authentication using ajax/json. So after successfull authentication I want to receive user object in my AngularJS app, otherwise error message. Any suggestions?

**Comment by kasperisager** [comment]
Most Passport strategies rely on redirecting to a third-party provider for authentication which won't work with async requests. I had to do what you're describing a couple of months back and ended up writing a custom authentication policy instead of using the generated auth layer.

**Comment by siready** [comment]
Would you please care to elaborate a bit more on a solution?

**Comment by kasperisager** [comment]
This article does a pretty good job at explaining the whole issue: http://blog.vjeux.com/2012/javascript/github-oauth-login-browser-side.html

**Comment by benoithubert** [comment]
I'm not sure that Joseph's question is about 100% client-side authentication.
As for me, I've been using sails-generate-auth to get a user object in my Ember.js app, but in order to do so, I had to tweak the AuthController, and to replace all the res.redirect(...) with res.json(...) in which I put either error codes, or relevant data (e.g. user) on success.
