### ISSUE TITLE
Google Auth seems to redirect back to login page even after successful login. 

### ISSUE THREAD

**Issue by iDVB** [kasperisager/sails-generate-auth#170]
Google Auth seems to redirect back to login page even after successful login. I even put a console.log in the AuthController.callback() and it never seem to get hit.

Not sure if this is correct, but I tried setting the callbackURL in the `passport.js` but still no dice.

```javascript
  google: {
    name: 'Google',
    protocol: 'oauth2',
    strategy: require('passport-google-oauth').OAuth2Strategy,
    options: {
      clientID: '[mynumhere]',
      clientSecret: '[mynumhere]',
      scope: ['email'],
      callbackURL: 'http://localhost:1337/auth/google/callback'
    }
  }
```

**Comment by tommykennedy** [comment]
You should use it like this. Scope sits outside options. 
 
   google: {
        name: 'Google',
        protocol: 'oauth2',
        strategy: require('passport-google-oauth').OAuth2Strategy,
        options: {
            clientID: 'xxx',
            clientSecret: 'xxx'
        },
        scope: ['email']
    },

**Comment by MinusRave** [comment]
I have the same issue and can't figure out what's wrong.

**Comment by zenvisuals** [comment]
I had the same problem, i managed to solve it. Scope can still be inside options. My User model was giving me the problems. After the passport authentication, if the authentication is successful on Google's site its suppose to give you the email of the user. I made the username and email attributes of my User model required input, and because Google only gave me back the email, the whole validation failed and it cannot proceed on creating a new user. So make sure the username and email attributes do not require input. Same goes for the password attribute in Passport model, make sure its not required as well.

**Comment by diogoviannaaraujo** [comment]
Im having this too, is not the user problem or the scope problem, i just get back tô login, user does not get created, connect does not run, on the callback action is undefined, so he just into every else until this.authenticate(provider, next)(req, res, req.next);
Been fighting with this for hours...

**Comment by melvin15may** [comment]
I was facing the same problem.  I added the new scope types.

```
 google: {
            options: {
                clientID: 'your client ID',
                clientSecret: 'your client secret',
                scope: ['https://www.googleapis.com/auth/plus.login', 'https://www.googleapis.com/auth/plus.profile.emails.read']
            },
        }
```

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
